### ISSUE TITLE
add  TUI functionalities

### ISSUE THREAD

**Issue by Raffaello** [Raffaello/sdl2-vga-terminal#133]
_if not keep simple at this prototyping/inception phase, it will become a project itself._

_just keep it simple, not perfect, but just some "raw" TUI functionalities._

----

some basic TUI functionalities:

***phase 1 (algorithmic):***

- [x] background
- [x] Header
- [x] footer
- [x] dialog single border
- [x] dialog mixed border
- [x] dialog header, body
- [x] dialog title, body
- [x] progress bar
- [x] [shadows]

goal of the ticket: _Tui version 0.1 (codename: **showcase**)_

------

***phase 2 (OOP design):***
~~- [ ] container~~
~~- [ ] interface~~

[skip] follow up ticket #136 

----

***phase 3:***
- [x] example
- [x] add a tui snapshot test
- [x] add `README` paragraph

**Comment by Raffaello** [comment]
now it is just a bare silly example, just for fun of coding some retro TUI style, but far to be really complete, anyway `v0.1-showcase`, right? :feelsgood:
